steps:
  - name: maven:3.8.6-openjdk-18
    id: deploy_services
    env:
      - 'TAGGING_DISPATCHER_GCS_IMAGE=${_TAGGING_DISPATCHER_GCS_IMAGE}'
      - 'TAGGER_GCS_IMAGE=${_TAGGER_GCS_IMAGE}'
    script:

      set -e
      
      echo "TAGGING_DISPATCHER_GCS_IMAGE = ${TAGGING_DISPATCHER_GCS_IMAGE}"
      echo "TAGGER_GCS_IMAGE = ${TAGGER_GCS_IMAGE}"

      mvn install
    
      mvn compile jib:build -f=dispatcher-tagging-gcs-app/pom.xml -Dimage="${TAGGING_DISPATCHER_GCS_IMAGE}"

      mvn compile jib:build -f=tagger-gcs-app/pom.xml -Dimage="${TAGGER_GCS_IMAGE}"



