
steps:
  - name: maven:3.8.6-openjdk-18
    id: deploy_services
    env:
      - 'IMAGE_NAME=${_IMAGE_NAME}'
    script:

      set -e

      echo "IMAGE_NAME = ${IMAGE_NAME}"
      
      mvn install jib:build -Dimage="${IMAGE_NAME}"



